version: '3.8'

services:
  php:
    build: .docker/php
    container_name: nette_php
    hostname: nette_php
    environment:
      APP_URL: fe.localhost
      ENVIRONMENT: 'develop'
      NETTE_DEBUG: 1
      PHP_EXTENSION_XDEBUG: 1
      PHP_EXTENSION_PGSQL: 0
      PHP_EXTENSION_PDO_PGSQL: 0
      PHP_EXTENSION_MYSQLI: 1
    volumes:
      - ./:/var/www/html/
    networks:
      - main_network

  caddy:
    image: caddy:latest
    networks:
      - main_network
    environment:
      VIRTUAL_HOST: fe.localhost
      VIRTUAL_PORT: 15423
      VIRTUAL_PATH: '/'
    volumes:
      - ./:/var/www/html/
      - .docker/caddy/Caddyfile:/etc/caddy/Caddyfile

  mysql:
    image: mysql:latest
    container_name: nette_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: default
      MYSQL_USER: default
      MYSQL_PASSWORD: secret
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - main_network

volumes:
  mysql:

networks:
  main_network:
    external: true